# Autogenerated wrapper script for GAP_pkg_edim_jll for aarch64-linux-musl
export ediv

using GAP_jll
JLLWrappers.@generate_wrapper_header("GAP_pkg_edim")
JLLWrappers.@declare_file_product(ediv)
function __init__()
    JLLWrappers.@generate_init_header(GAP_jll)
    JLLWrappers.@init_file_product(
        ediv,
        "lib/gap/ediv.so",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
